### ISSUE TITLE
Local mode, manifest file (paired-end samples) throws errors

### ISSUE THREAD

**Issue by lcolladotor** [nellore/rail#30]
Hi,

I believe that my manifest file is correct. That is, I have:

```
<local path pair1><tab><0><tab><local path pair2><tab><0><tab><sample name>
```

But when I run the `rail prep local` step, I get errors like this:

```
Rail-RNA v0.1.9c
Loading...
Traceback (most recent call last):
  File "/jhpce/shared/community/compiler/gcc/4.4.7/python/2.7.9/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/jhpce/shared/community/compiler/gcc/4.4.7/python/2.7.9/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/bst/student/lcollado/raildotbio/rail-rna/__main__.py", line 725, in <module>
    scratch=args.scratch
  File "/home/bst/student/lcollado/raildotbio/rail-rna/rna/driver/rna_config.py", line 4610, in __init__
    raise_runtime_error(base)
  File "/home/bst/student/lcollado/raildotbio/rail-rna/rna/driver/rna_config.py", line 1189, in raise_runtime_error
    ) if len(bases.errors) > 1 else bases.errors[0]
RuntimeError: 1) The following line from the manifest file /dcs01/ajaffe/Brain/derRuns/derSupplement/simulation/rail/rail-manifest.txt has an invalid sample label:
/dcs01/ajaffe/Brain/derRuns/derSupplement/simulation/simulated_reads/sample_01_1.fasta.gz	0	/dcs01/ajaffe/Brain/derRuns/derSupplement/simulation/simulated_reads/sample_01_2.fasta.gz	0	sample1G1R1
A valid sample label takes the following form:
<Group ID>-<BioRep ID>-<TechRep ID>
2) The following line from the manifest file /dcs01/ajaffe/Brain/derRuns/derSupplement/simulation/rail/rail-manifest.txt has an invalid sample label:
/dcs01/ajaffe/Brain/derRuns/derSupplement/simulation/simulated_reads/sample_02_1.fasta.gz	0	/dcs01/ajaffe/Brain/derRuns/derSupplement/simulation/simulated_reads/sample_02_2.fasta.gz	0	sample2G1R1
A valid sample label takes the following form:
<Group ID>-<BioRep ID>-<TechRep ID>
```

From the error I can see that `rail` is thinking that I'm on single-end mode instead of paired-end. Also, I don't think that my manifest file is different from https://github.com/nellore/rail/blob/master/eval/GEUVADIS_28_local.manifest so I'm not sure what's wrong.

## Details

[manifest file](https://github.com/lcolladotor/derSupplement/blob/3b00a15773fbcb60a2e750b2cbb3a3b04c9bb18c/simulation/rail/rail-manifest.txt) which gets created by [this script](https://github.com/lcolladotor/derSupplement/blob/3b00a15773fbcb60a2e750b2cbb3a3b04c9bb18c/simulation/rail/prep-manifest.R)
[script for local rail](https://github.com/lcolladotor/derSupplement/blob/3b00a15773fbcb60a2e750b2cbb3a3b04c9bb18c/simulation/rail/run-rail.sh) currently failing at `rail prep local` step.

I'm using  v0.1.9c which is the latest non-devel version. Should I switch to the devel one?

**Comment by nellore** [comment]
A sample label must have two hyphens in versions of Rail-RNA <= 0.1.9c. In future versions, this restriction will be removed. Thanks for the detailed report!
