### ISSUE TITLE
make_it_rail requires verve@verve.webfactional.com's password

### ISSUE THREAD

**Issue by BenLangmead** [nellore/rail#40]
I am trying to run `make_it_rail.sh` per the manual (http://docs.rail.bio/installation/) but it needs verve@verve.webfactional.com's password:

```
$ sh make_it_rail.sh
  adding: __main__.py (deflated 89%)
  adding: cloudformation/ (stored 0%)
  adding: cloudformation/dbgap.template (deflated 80%)
  (snip)
  adding: rna/utils/tempdel.py (deflated 55%)
  adding: version.py (deflated 20%)
Installer created at /Users/langmead/git/rail/releases/install_rail-rna-devel .
Copying to webfactional... .
verve@verve.webfactional.com's password:
```

**Comment by BenLangmead** [comment]
I see now that the scp is actually an upload that presumably is only relevant when you do it.  So maybe solution is as simple as protecting the scp with a "--admin-upload" flag or the like

**Comment by nellore** [comment]
`make_it_rail.sh` now uploads to webfaction if and only if the `-u` parameter is invoked; see 4a85806.
