### ISSUE TITLE
Try harder to find pypy version number in pypy --version output

### ISSUE THREAD

**Issue by BenLangmead** [nellore/rail#42]
E.g., this output for `pypy --version` results in Rail-RNA complaining I don't have the right version:

```
$ pypy --version
Python 2.7.10 (5f8302b8bf9f53056e40426f10c72151564e5b19, Feb 11 2016, 20:38:54)
[PyPy 4.0.1 with GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

Because the check is too restrictive:

https://github.com/nellore/rail/blob/3e1491621850a4b5274580fb8289c0afbba45a8d/src/rna/driver/rna_config.py#L191

**Comment by nellore** [comment]
Resolved in f5b6338.
