### ISSUE TITLE
output_dir and mover not defined previously in stream_and_upload

### ISSUE THREAD

**Issue by BenLangmead** [nellore/rail#44]
Looks like `output_dir` and `mover` aren't defined before being used in the `stream_and_upload` function:

https://github.com/nellore/rail/blob/6a0a3c22c1e1d0b12f0fa7211e74a830b19b1e7c/src/rna/steps/bam.py#L325
https://github.com/nellore/rail/blob/6a0a3c22c1e1d0b12f0fa7211e74a830b19b1e7c/src/rna/steps/bam.py#L333

**Comment by nellore** [comment]
Verified that this is just PyCharm being overly sensitive.
