### ISSUE TITLE
error when specifying -r parameter...

### ISSUE THREAD

**Issue by nickschurch** [nellore/rail#46]
I recently tried a local rail-RNA run on one of our compute nodes here. I specified "-r 1000000" for the sort-memory-cap and got the following error:

Loading...
Detected Bowtie 1 v1.1.1, Bowtie 2 v2.2.5, and SAMTools v1.2.1.
Launching Dooplicity runner with PyPy...
ningal.cluster.lifesci.dundee.ac.uk > tail -f rail-rna.e1288159
Detected Bowtie 1 v1.1.1, Bowtie 2 v2.2.5, and SAMTools v1.2.1.
Launching Dooplicity runner with PyPy...
usage: emr_simulator.py [-h] [-m MEMCAP] [-p NUM_PROCESSES] [-t MAX_ATTEMPTS]
                        [-s SEPARATOR] [-k] [--keep-last-output]
                        [--gzip-outputs] [--gzip-level GZIP_LEVEL] [--ipy]
                        [--ipcontroller-json IPCONTROLLER_JSON]
                        [--ipy-profile IPY_PROFILE] [--scratch SCRATCH]
                        [--common COMMON] [--sort SORT] [-b BRANDING]
                        [-j JSON_CONFIG] [-f] [-l LOG]
emr_simulator.py: error: argument -m/--memcap: invalid int value: '1000000000.0'

It looks like the command line input is being read as a float when an int is expected. Removing the -r parameter removes the issue.

**Comment by nellore** [comment]
Hi Nick,

I'm having trouble reproducing this error. Could you please tell me the output of `rail-rna --version` and give me the precise command you used to run Rail?

Best,
Abhi

**Comment by nickschurch** [comment]
sure. I'm new to rail so I was testing it by running a local run on one of
our cluster nodes via qsub. The command was:

qsub -b y -V -cwd -pe smp 30 -l ram=1G -q c6145-long.q rail-rna go local -x
pathto/BowtieIndex/genome pathto/Bowtie2Index/genome -m
pathto/railRNA.manifest --do-not-output-bam-by-chr
--do-not-output-ave-bw-by-chr -p 30 -r 1000000

the version is rail-rna-0.1.9a

**Comment by nellore** [comment]
Hi Nick,

Thanks for the details! Upgrading to v0.2.3b of Rail-RNA at http://rail.bio/ will solve this problem.

Best,
Abhi

**Comment by nickschurch** [comment]
OK, but I only got it installed this morning from your main install pages! (
http://rail.bio)

How can it be out of date already?!

**Comment by nellore** [comment]
It's possible there's another Rail install in a different directory. I can help you diagnose in https://gitter.im/nellore/rail if you're having trouble.
