### ISSUE TITLE
Calculate AUC for each sample

### ISSUE THREAD

**Issue by lcolladotor** [nellore/rail#47]
Hi,

To be consistent with `recount`, it'll be great if `Rail-RNA` includes in `counts.tsv.gz` the AUC for each sample.

Best,
Leo

**Comment by lcolladotor** [comment]
https://github.com/leekgroup/recount-website/blob/master/recount-prep/prep_sample.R#L72-L79 does the job, so it's not really needed anymore.

**Comment by nellore** [comment]
True that!
