### ISSUE TITLE
Resolve error on NoSuchLifecycleConfiguration

### ISSUE THREAD

**Issue by BenLangmead** [nellore/rail#59]
I find that when I create a new bucket from the AWS CLI, it doesn't have lifecycle enabled by default.  This causes an error here:

https://github.com/nellore/rail/blob/5748f5f20eddf8cd2fd1bb92646b509d7dba6798/src/dooplicity/ansibles.py#L356

But seems like it shouldn't.  @nellore commented that he things the check should be a `not in errors` rather than an `in errors`, but I defer on what the best solution is.

**Comment by BenLangmead** [comment]
Nudge

**Comment by nellore** [comment]
Done!
