### ISSUE TITLE
Optionally skip "Copying Rail-RNA and bootstraps to S3..."

### ISSUE THREAD

**Issue by BenLangmead** [nellore/rail#64]
Sometimes I am running the tool in elastic mode just to get a json file (with `--json`) and not to actually start a job.  In that case, I'd like to suppress the uploading of the software to S3, which can be slow over a slow connection.

**Comment by nellore** [comment]
addressed in https://github.com/nellore/rail/commit/8aeda6517dda852208ec78ee90b383f87de0a3d2; use `--json` in conjunction with `--no-setup` in all modes to perform a minimum of checks, bar uploads, and obtain job flow JSON.
